version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: Europe/Vienna
      WEBPASSWORD: Password
    volumes:
      - 'etcd:/etc/pihole'
      - 'dnsmasq:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - macvlan
    networks:
      macvlan:
        ipv4_address: 192.168.10.200

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
volumes:
  etcd:
  dnsmasq:


